name: fruits_app
description: Online Fruits shopping app UI
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  flutter_staggered_grid_view: ^0.5.0
  path_provider: ^2.0.8
  font_awesome_flutter: ^9.2.0
  fluttertoast: ^8.0.8

  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  assets:
    - assets/