name: Remove_Bloatware
description: Details of installed and system apps in your smartphone and a step
  by step guide to remove all Remove_Bloatware

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations: ^1.1.2
  cupertino_icons: ^1.0.0
  device_apps: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
